spring:
  application:
    name: iko-layout-converter
  main:
    web-application-type: none

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

migration:
  source-schema: ${IKO_SOURCE_SCHEMA:SOURCE_SCHEMA}
  target-schema: ${IKO_TARGET_SCHEMA:TARGET_SCHEMA}
  commit-size: ${IKO_COMMIT_SIZE:10000}
  tasks: ${IKO_TASKS:}
