CREATE TABLE EXECUTION_CONTROL (
    RUN_ID VARCHAR2(36 CHAR) NOT NULL,
    TASK_ID VARCHAR2(128 CHAR) NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    START_AT TIMESTAMP NOT NULL,
    END_AT TIMESTAMP NULL,
    CONSTRAINT PK_EXECUTION_CONTROL PRIMARY KEY (RUN_ID, TASK_ID),
    CONSTRAINT CK_EXECUTION_CONTROL_STATUS CHECK (
        STATUS IN ('RUNNING', 'SUCCESS', 'ERROR', 'SKIPPED')
    )
);

CREATE INDEX IX_EXECUTION_CONTROL_01
    ON EXECUTION_CONTROL (TASK_ID, START_AT DESC);

