CREATE TABLE SAMPLE_CUSTOMER_001 (
    SOURCE_KEY VARCHAR2(32 CHAR) NOT NULL,
    CUSTOMER_NAME VARCHAR2(120 CHAR),
    BIRTH_YY VARCHAR2(4 CHAR),
    BIRTH_MM VARCHAR2(2 CHAR),
    BIRTH_DD VARCHAR2(2 CHAR),
    CONSTRAINT PK_SAMPLE_CUSTOMER_001 PRIMARY KEY (SOURCE_KEY)
);

CREATE TABLE SAMPLE_CUSTOMER_002 (
    SOURCE_KEY VARCHAR2(32 CHAR) NOT NULL,
    AMOUNT NUMBER(15, 0),
    CONSTRAINT PK_SAMPLE_CUSTOMER_002 PRIMARY KEY (SOURCE_KEY)
);

CREATE TABLE SAMPLE_CUSTOMER (
    CUSTOMER_ID VARCHAR2(32 CHAR) NOT NULL,
    CUSTOMER_NAME VARCHAR2(120 CHAR),
    BIRTHDAY VARCHAR2(8 CHAR),
    AMOUNT NUMBER(15, 0),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_SAMPLE_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);

